package accounts;


//import java.sql.Date;
import accounts.Account;
import java.sql.*;
import java.io.*;
import java.util.Date;
import java.text.ParseException;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aditya
 */
//This GUI displays all the transactions between two dates
public class AccountDetailsGUI extends javax.swing.JFrame {

    /**
     * Creates new form accountDetailsGUI
     */
    private static final String rootUsername="root";
    private static final String rootPassword="password";
    private static final String conn_string="jdbc:mysql://localhost:3306/UDIS";
    private Connection conn=null;
    private String fromdate;
    private String todate;
    DefaultTableModel model;
    Date date1=new Date();
    Date date2=new Date();
    public AccountDetailsGUI() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(44, 62, 80));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        balanceField = new javax.swing.JTextField();
        expenditureField = new javax.swing.JTextField();
        incomeField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fromDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        toDate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        deptAccount = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("ACCOUNT DETAILS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Account Holder", "Account Number", "Purpose", "Amount", "Credit/Debit"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Income  :");

        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Expenditure :");

        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Balance :");

        balanceField.setEditable(false);

        expenditureField.setEditable(false);

        incomeField.setEditable(false);

        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("From :");

        fromDate.setText("yyyy-mm-dd");
        fromDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromDateActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("To :");

        toDate.setText("yyyy-mm-dd");
        toDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toDateActionPerformed(evt);
            }
        });

        jButton1.setText("Get Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("Department Account Number :");

        deptAccount.setEditable(false);
        deptAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptAccountActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jButton5.setText("X");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel5)
                        .addGap(50, 50, 50)
                        .addComponent(fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166)
                        .addComponent(jLabel6)
                        .addGap(41, 41, 41)
                        .addComponent(toDate, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel7)
                        .addGap(51, 51, 51)
                        .addComponent(deptAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(incomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expenditureField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(balanceField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(281, 281, 281)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(354, 354, 354))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(incomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(expenditureField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(balanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(toDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(deptAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fromDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromDateActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_fromDateActionPerformed

    private void toDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toDateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        incomeField.setText("");
        deptAccount.setText("");
        expenditureField.setText("");
        balanceField.setText("");
        model= (DefaultTableModel)jTable1.getModel();
        model.setNumRows(0);
        fromdate=fromDate.getText();
        todate=toDate.getText();
           int flag=0;
        try { 
           date1= new SimpleDateFormat("yyyy-MM-dd").parse(fromdate);
           date2= new SimpleDateFormat("yyyy-MM-dd").parse(todate);
        } catch (ParseException ex) {
            javax.swing.JOptionPane.showMessageDialog(getContentPane(),"Incorrect Date Format");
            
            fromDate.setText("yyyy-mm-dd");
            toDate.setText("yyyy-mm-dd");
            flag=1;
            
        }
        if(date1.compareTo(date2)>0)
        {
                 javax.swing.JOptionPane.showMessageDialog(getContentPane(),"Wrong Dates");
                 fromDate.setText("yyyy-mm-dd");
                  toDate.setText("yyyy-mm-dd");
                  flag=1;
        }
        if(flag==0)
        {
            ArrayList<Transaction> List;
            List = new ArrayList<>();
            try
            {
                conn= DriverManager.getConnection(conn_string, rootUsername, rootPassword);
                 Statement st=(Statement) conn.createStatement();
                
                 String query="SELECT * FROM accounts where date between' "+fromdate+" 'AND '"+todate+"' ORDER by date";
                  ResultSet rs=st.executeQuery(query);
                 Transaction t1;
                while(rs.next())
                {
                    
                    t1=new Transaction(rs.getString("purpose"),rs.getFloat("amount"),rs.getDate("date"),rs.getString("accountHolder"),rs.getString("accountNumber"),rs.getInt("transactionType"));
                    List.add(t1);
                }
                float income=0;
                float expenditure=0;
                Object[] row=new Object[6];
                for(int i=0;i<List.size();i++)
                {
                    row[0]=List.get(i).getDate();
                    row[1]=List.get(i).getAccountHolder();
                    row[2]=List.get(i).getAccountNumber();
                    row[3]=List.get(i).getPurpose();
                    row[4]=List.get(i).getAmount();
                    row[5]=List.get(i).getType();
                    if(List.get(i).getType()=="Credit")
                    {
                        income=income+List.get(i).getAmount();
                    }
                    if(List.get(i).getType()=="Debit")
                    {
                        expenditure=expenditure+List.get(i).getAmount();
                    }
                    model.addRow(row);
                }
                 String query2="SELECT * FROM accounts WHERE id = (SELECT MAX(id) FROM accounts);";
                 rs=st.executeQuery(query2);
                 rs.next();
                 float balance=rs.getFloat("currentBalance");
                 Account a2=new Account();
                 deptAccount.setText(a2.getAccountNumber());
                 incomeField.setText(Float.toString(income));
                 expenditureField.setText(Float.toString(expenditure));
                 balanceField.setText(Float.toString(balance));
            }
            catch(SQLException e)
            {
                  System.err.println(e);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deptAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptAccountActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ManageAccountGUI().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balanceField;
    private javax.swing.JTextField deptAccount;
    private javax.swing.JTextField expenditureField;
    private javax.swing.JTextField fromDate;
    private javax.swing.JTextField incomeField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField toDate;
    // End of variables declaration//GEN-END:variables
}
