package accounts;

import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aditya
 */
//This GUI enters the transaction info into database
//Debit and Credit information can be added to database
public class DebitCreditGUI extends javax.swing.JFrame {

    /**
     * Creates new form debitCreditGUI
     */
    private static final String rootUsername="root";
    private static final String rootPassword="password";
    private static final String conn_string="jdbc:mysql://localhost:3306/UDIS";
    private Connection conn=null;
    private String accountNumber;
    private String accountHolder;
    private String purposeoftransaction;
    private String amount;
    private String type;
    private String datestr;
    private float amountentered;
    Date dateoftransaction;
    public DebitCreditGUI() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(44, 62, 80));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        accountholder = new javax.swing.JTextField();
        accountnumber = new javax.swing.JTextField();
        purpose = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        amountvalue = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("DEBIT/CREDIT INFORMATION");

        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Date");

        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Account Holder");

        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Account Number");

        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Purpose");

        date.setText("yyyy-mm-dd");
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });

        accountnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountnumberActionPerformed(evt);
            }
        });

        purpose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purposeActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Debit Amount", "Credit Amount" }));

        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Amount");

        amountvalue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountvalueActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("Credit/Debit");

        jButton1.setText("Add Information");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jButton5.setText("X");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date)
                            .addComponent(accountholder)
                            .addComponent(accountnumber)
                            .addComponent(purpose)
                            .addComponent(amountvalue))
                        .addGap(123, 123, 123))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(218, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(77, 77, 77)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(accountholder, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(accountnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purpose, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(amountvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountnumberActionPerformed

    private void purposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purposeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purposeActionPerformed

    private void amountvalueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountvalueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountvalueActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       accountHolder=accountholder.getText();
        accountNumber=accountnumber.getText();
        amount=amountvalue.getText();
        type=(String)jComboBox1.getSelectedItem();
        datestr=date.getText();
        purposeoftransaction=purpose.getText();
        accountHolder=accountHolder.trim();
        accountNumber=accountNumber.trim();
        amount=amount.trim();
        datestr=datestr.trim();
        purposeoftransaction=purposeoftransaction.trim();
        int flag=0;
        try
        {
            amountentered=Float.parseFloat(amount);
        }
        catch(NumberFormatException e)
        {
            javax.swing.JOptionPane.showMessageDialog(getContentPane(),"Invalid amount format");
            flag=1;
        }
        if(amountentered<0)
        {
            javax.swing.JOptionPane.showMessageDialog(getContentPane(),"Amount cannot be negative");
            flag=1;
        }
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        try
        {
            dateoftransaction=formatter.parse(datestr);
        }
        catch(ParseException e)
        {
            javax.swing.JOptionPane.showMessageDialog(getContentPane(),"Invalid date format");
            flag=1;
        }
         if(accountHolder.equals("")||accountNumber.equals("")||amount.equals("")||datestr.equals("")||purposeoftransaction.equals(""))
         {
             flag=1;
             javax.swing.JOptionPane.showMessageDialog(getContentPane(),"Information Fields cannot be empty");
         }
         if(flag==0)
         {
            try
            {
                conn= DriverManager.getConnection(conn_string, rootUsername, rootPassword);
                Statement st=(Statement) conn.createStatement();
                if(type=="Credit Amount")
                {
                
                
                    String query2="SELECT * FROM accounts WHERE id = (SELECT MAX(id) FROM accounts);";
                    ResultSet rs=st.executeQuery(query2);
                    rs.next();
                
                    float currentbal=rs.getFloat("currentBalance");
                    currentbal=currentbal+amountentered;
                    String query="INSERT into accounts(currentBalance,date,purpose,accountHolder,accountNumber,amount,transactionType) values (?,?,?,?,?,?,?)";
                    PreparedStatement stmt=conn.prepareStatement(query);
                    stmt.setFloat(1, currentbal);
                    java.sql.Date sqlDate = new java.sql.Date(dateoftransaction.getTime());
                    stmt.setDate(2,sqlDate);
                    stmt.setString(3,purposeoftransaction );
                    stmt.setString(4,accountHolder);
                    stmt.setString(5,accountNumber);
                    stmt.setFloat(6,amountentered);
                    stmt.setInt(7,1);
                    stmt.executeUpdate();  
                    javax.swing.JOptionPane.showMessageDialog(getContentPane(),"Amount Credit Information Added");
                }
                
                if(type=="Debit Amount")
                {
                
                
                    String query2="SELECT * FROM accounts WHERE id = (SELECT MAX(id) FROM accounts);";
                    ResultSet rs=st.executeQuery(query2);
                    rs.next();
                
                    float currentbal=rs.getFloat("currentBalance");
                    currentbal=currentbal-amountentered;
                    String query="INSERT into accounts(currentBalance,date,purpose,accountHolder,accountNumber,amount,transactionType) values (?,?,?,?,?,?,?)";
                    PreparedStatement stmt=conn.prepareStatement(query);
                    stmt.setFloat(1, currentbal);
                 

                    java.sql.Date sqlDate = new java.sql.Date(dateoftransaction.getTime());
                    stmt.setDate(2,sqlDate);
                    stmt.setString(3,purposeoftransaction );
                    stmt.setString(4,accountHolder);
                    stmt.setString(5,accountNumber);
                    stmt.setFloat(6,amountentered);
                    stmt.setInt(7,2);
                    stmt.executeUpdate();  
                    javax.swing.JOptionPane.showMessageDialog(getContentPane(),"Amount Debit Information Added");
                }
                accountholder.setText("");
                accountnumber.setText("");
                amountvalue.setText("");
                date.setText("yyyy-mm-dd");
                purpose.setText("");
            }
            catch(SQLException e)
            {
                System.err.println(e);
            }
         }
             
            
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ManageAccountGUI().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void main(String[] args) {
        new DebitCreditGUI().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountholder;
    private javax.swing.JTextField accountnumber;
    private javax.swing.JTextField amountvalue;
    private javax.swing.JTextField date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField purpose;
    // End of variables declaration//GEN-END:variables
}
