package ds;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gurjot273
 */
import java.sql.*;

//GUI for registering courses in current semester of student
public class StudentRegistrationGUI extends javax.swing.JFrame {

    /**
     * Creates new form StudentRegistration
     */
    private static final String rootUsername="root";
    private static final String rootPassword="password";
    private static final String conn_string="jdbc:mysql://localhost:3306/UDIS";
    private Connection conn;
    private StudentRegistration studentRegistration;
    
    public boolean IsAnyFieldEmpty(){
        return jTextField1.getText().trim().length()==0 || jTextField2.getText().trim().length()==0; 
    }
    
    public StudentRegistrationGUI(StudentRegistration studentRegistration) {
        this.studentRegistration=studentRegistration;
        initComponents();
        getContentPane().setBackground(new java.awt.Color(123, 239, 178));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("STUDENT COURSE REGISTRATION");

        jLabel2.setText("Roll Number");

        jLabel3.setText("Course ID");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("Register Student");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    //checks the fields and registers the student
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.conn=null;
        try{
            conn= DriverManager.getConnection(conn_string, rootUsername, rootPassword);
            Statement st=(Statement) conn.createStatement();
            if(!IsAnyFieldEmpty())
            {
                String query="SELECT * FROM ds";
                ResultSet rs=st.executeQuery(query);
                rs.next();
                int semester=rs.getInt("semester");
                int year=rs.getInt("ongoingYear");
                query="SELECT * FROM students WHERE rollNumber='"+jTextField1.getText()+"'";
                rs=st.executeQuery(query);
                if(!rs.next()){
                    javax.swing.JOptionPane.showMessageDialog(getContentPane(),"Roll Number not present");
                }else{
                    studentRegistration.rollNumber=jTextField1.getText();
                    int studentId=rs.getInt("id");
                    query="SELECT * FROM courses WHERE courseId='"+jTextField2.getText()+"' AND studentId='"+studentId+"' AND year='"+year+"' AND semester='"+semester+"'";
                    rs=st.executeQuery(query);
                    if(!rs.next()){
                        query="SELECT * FROM courses WHERE courseId='"+jTextField2.getText()+"' AND studentId is NULL"+" AND year='"+year+"' AND semester='"+semester+"'";
                        rs=st.executeQuery(query);
                        if(!rs.next()){
                            javax.swing.JOptionPane.showMessageDialog(getContentPane(),"Course ID not present for current semester");
                        }else{
                            query="INSERT INTO courses (courseId,name,studentId,instructorId,year,semester,credits) VALUES ('"+rs.getString("courseId")+"','"+rs.getString("name")+"','"+studentId+"','"+rs.getInt("instructorId")+"','"+rs.getInt("year")+"','"+rs.getInt("semester")+"','"+rs.getInt("credits")+"')" ;
                            try{
                                st.executeUpdate(query);
                                javax.swing.JOptionPane.showMessageDialog(getContentPane(),"Student Successfully Registered in course");
                            }catch(SQLException e){
                                javax.swing.JOptionPane.showMessageDialog(getContentPane(),"Error occurred.Try again");
                            }
                        }
                    }else{
                        javax.swing.JOptionPane.showMessageDialog(getContentPane(),"Student already registered in course");
                    }
                }
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(getContentPane(),"Input fields cannot be empty or contain only spaces");
            }
            jTextField1.setText("");
            jTextField2.setText("");
        }catch(SQLException e){
            System.err.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    //back button
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new SemesterRegistrationGUI().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
